In [12]:
#polynomes
import numpy as np

Polynomial = np.polynomial.Polynomial

X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,2,1,4,3])

points,stats = Polynomial.fit(X,Y,1,full=True)#1 means equ of 1 degree 5.5x -4.5 

print(points,'\n',stats)


5.499999999999999 - 4.063636363636364 x**1 
 [array([15.22424242]), 2, array([1., 1.]), 2.220446049250313e-15]


In [16]:


from numpy import *

a = poly1d((-7))
b = poly1d((-7,2))
c = poly1d((-7,2,1))
d = poly1d((-7,2,1,3))
e = poly1d((-7,2,1,3,6))


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


In [17]:
from numpy import *

a = poly1d((-7,2,1,3,6))

b=a(5) #plug this number into x to get the value of polynom as a whole
c=a(0)
d=a(-15)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)


    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------
-4079
-------------------------
6
-------------------------
-360939


In [21]:
from numpy import *

a = polyval((1,2),2) #poly with the value of x
b = polyval((1,2,3),7)
c = polyval((1,2,3,5),-3)
d = polyval((1,2,3,5,-6),12.6)


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

4
-------------------------
66
-------------------------
-13
-------------------------
29738.769599999992


In [23]:
from numpy import *
#derevitive

a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2) 
c =polyder(poly1d((1,2,3)),3)# number of drevetive

d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


 
2 x + 2
-------------------------
 
2
-------------------------
 
0
-------------------------
   3     2
4 x + 6 x + 6 x + 5
-------------------------
 
24 x + 12


In [26]:


from numpy import *

a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2)
c =polyder(poly1d((1,2,3)),3)
d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a(4))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))


10
-------------------------
2
-------------------------
0
-------------------------
1
-------------------------
132


In [29]:
#integration
from numpy import *

a =polyint(poly1d((1,2,3)))
b =polyint(poly1d((1,2,3)),2)
c =polyint(poly1d((1,2,3)),3)

d =polyint(poly1d((1,2,3,5,12)))
e =polyint(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e(5))


        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------------------------
1168.8988095238094


In [37]:
#solutions of equation its roots
from numpy import *


a =roots(poly1d((1,2)))
b =roots(poly1d((1,2,3)))
c =roots(poly1d((1,2,3,5)))
d =roots(poly1d((1,2,3,5,12)))
e =roots(poly1d((1,2,3,5,12,22)))
# J imaginary nm


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print (e)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)



[-2.]
-------------------------
[-1.+1.41421356j -1.-1.41421356j]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]


In [38]:


from numpy import *

x = array([3,6,2,5,4])
y = array([2,3,-9,6,2.5])
z = polyfit(x, y, 2)


print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)
print('-------------------------')



[3 6 2 5 4]
-------------------------
[ 2.   3.  -9.   6.   2.5]
-------------------------
[ -1.78571429  17.08571429 -35.3       ]
-------------------------


In [48]:
#dates

from numpy import *
x = array('2022-07-04', dtype=datetime64)

print(x)
print('-------------------------')



2022-07-04
-------------------------


In [49]:

from numpy import *
x = datetime64('2022-04-23')
print(x)
print('-------------------------')


2022-04-23
-------------------------


In [52]:
from numpy import *
x = datetime64('2021-07-25')

y = x + arange(12) #range is a list but aranage is matrix

print(x)
print('-------------------------')
print(y)


2021-07-25
-------------------------
['2021-07-25' '2021-07-26' '2021-07-27' '2021-07-28' '2021-07-29'
 '2021-07-30' '2021-07-31' '2021-08-01' '2021-08-02' '2021-08-03'
 '2021-08-04' '2021-08-05']


In [2]:
from numpy import *
x = datetime64('2022-04-22')
y = datetime64('2022-05-11')

z = y-x

print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)


2022-04-22
-------------------------
2022-05-11
-------------------------
19 days


In [3]:
#fuction
from numpy import *

x = fromfunction(lambda i: i**3, (10,))# (10,) marix with one col

print(x)
print('-------------------------')


[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]
-------------------------
[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]
-------------------------


In [4]:
from numpy import *

x = fromfunction(lambda i: 3 * (i+5)**3, (10,))

print(x)
print('-------------------------')
x = fromfunction(lambda i,j: i+j, (4,5))

print(x)
print('-------------------------')


[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]
-------------------------


In [12]:
x = fromfunction(lambda i,j: i+j, (4,5))# i =4 and j=5 each element of i is add on row of j


print(x)
print('-------------------------')


[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]
-------------------------


In [14]:
from numpy import *

x = fromfunction(lambda i,j: 3*i*j, (4,5))

print(x)
print('-------------------------')


[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  6. 12. 18. 24.]
 [ 0.  9. 18. 27. 36.]]
-------------------------


In [15]:
from numpy import *

x = fromfunction(lambda i,j,k: i+j+k, (2,3,4))

print(x)
print('-------------------------')


[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]
-------------------------


In [5]:
from numpy import *

x = fromfunction(lambda i,j,k: (2*i)*(j**2)*k, (2,3,4))

print(x)
print('-------------------------')


[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  2.  4.  6.]
  [ 0.  8. 16. 24.]]]
-------------------------


In [23]:
from numpy import *

def powers(i):
    i = i**2
    return i
x = fromfunction(powers, (9,), dtype=int)

print(x)
print('-------------------------')


[ 0.  1.  4.  9. 16. 25. 36. 49. 64.]
-------------------------


In [25]:
from numpy import *

def powers(i,j):
    i = i**j
    return i


x = fromfunction(powers, (4,5), dtype=int)

print(x)
print('-------------------------')


[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
-------------------------


In [33]:
from numpy import *

m,n = 11, 5

def f(i):
    return (i % n == 0)
x = fromfunction(f, (m,), dtype=int)

print(x)
print('-------------------------')


[ True False False False False  True False False False False  True]
-------------------------
